### PR TITLE
Changing Build to Use a Prefix (And Fixing VSTS Build Issues)

### PR DESCRIPTION
**Pull request by Stewartarmbrecht**
## Purpose
I encountered several issues when trying to build and deploy the solution using VSTS.  In fixing them, I decided to simplify the deployment scripts to use a single globally unique prefix value and a naming convention that started with the resource groups.  

**I also updated the solution to use one instance of Application Insights with the hope that it's Application Map feature will help visualize the system once the Azure Functions team gets the dependencies working and AI.**

I updated all ARM templates and the documentation.  I also removed some unused ps1 scripts.

Below are the resources that will be created if you used 'serverlessstew' as your globally unique prefix.

|NAME|RESOURCE GROUP|TYPE|
|---|---|---|
|serverlessstew-audio-api|ServerlessStew-Audio|App Service|
|serverlessstew-audio-asp|ServerlessStew-Audio|App Service plan|
|serverlessstew-audio-cs|ServerlessStew-Audio|Cognitive Services|
|serverlessstew-audio-worker|ServerlessStew-Audio|App Service|
|serverlessstew-categories-api|ServerlessStew-Categories|App Service|
|serverlessstew-categories-asp|ServerlessStew-Categories|App Service plan|
|serverlessstew-categories-cs|ServerlessStew-Categories|Cognitive Services|
|serverlessstew-categories-db|ServerlessStew-Categories|Azure Cosmos DB account|
|serverlessstew-categories-worker|ServerlessStew-Categories|App Service|
|serverlessstew-events-topic|ServerlessStew-Events|Event Grid Topic|
|serverlessstew-images-api|ServerlessStew-Images|App Service|
|serverlessstew-images-asp|ServerlessStew-Images|App Service plan|
|serverlessstew-images-cs|ServerlessStew-Images|Cognitive Services|
|serverlessstew-images-worker|ServerlessStew-Images|App Service|
|serverlessstew-monitor-ai|ServerlessStew-Monitor|Application Insights|
|serverlessstew-proxy-api|ServerlessStew-Proxy|App Service|
|serverlessstew-proxy-asp|ServerlessStew-Proxy|App Service plan|
|serverlessstew-text-api|ServerlessStew-Text|App Service|
|serverlessstew-text-asp|ServerlessStew-Text|App Service plan|
|serverlessstew-text-db|ServerlessStew-Text|Azure Cosmos DB account|
|serverlessstew-web-app|ServerlessStew-Web|App Service|
|serverlessstew-web-asp-apps|ServerlessStew-Web|App Service plan|
|serverlessstewaudioblob|ServerlessStew-Audio|Storage account|
|serverlessstewimagesblob|ServerlessStew-Images|Storage account

Issue: #9 

## Does this introduce a breaking change?
```
[ X] Yes - I am working now to update the build scripts that were just merged.
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ X] Refactoring (no functional changes, no api changes)
[ X] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
Run the the setup.md steps for a VSTS build and deployment.

## What to Check
Verify that you do not get build or deployment errors and verify the app works after deployment.

### CODE REVIEW

**Comment by priyaananthasankar** [comment]
Please raise a pull request with only the web vsts change that gave a 404 in Angular app as the other changes in this PR, will change the way we wanted to design the VSTS templates (in a generic fashion) and break our scripts.

**Comment by priyaananthasankar** [comment]
@Stewartarmbrecht  Please don't change the build scripts. Will accept changes that are bug fixes to the current branch.

**Comment by Stewartarmbrecht** [comment]
@priyaananthasankar I already made the changes.  I'm just waiting for them to finish running to verify they work.

**Comment by priyaananthasankar** [comment]
I suggest this: Fork a branch of this repository and all these changes can be made there if it works well, but won't be able to accept this PR in the master branch. We have provided a generic way to setup this sample in the master branch as a base work. We can accept controlled changes but not the entire sample deployment change.
Two changes we can consider:

1. Angular app 404 VSTS change - fixes.
2. App insights unification.

So please do re-raise a PR with controlled changes.

**Comment by Stewartarmbrecht** [comment]
OK.  I'll do that.  

I understand that the PR is too big.  It's one of my first PRs and I didn't realize my commits to my fork would automatically be included in the PR after I issued it.  If you take just the first 6 commits you will get the 404 fixes.  

On the other hand, my last check-in includes working versions of your build.sh and deploy.sh scripts.  I also updated the documentation to include a step for installing Zip.  I've never used WSL before.  The directions are a little sparse but I was able to figure out how to get it to work.  I tested the updated build.sh and deploy.sh scripts and they both worked.  I also tested the deployed app and all major features were working.

While the PR looks like a lot of changes, it's mostly repetitive changes due to the naming convention change.

If you take the remaining commits you will get the following:

New Prefix based naming convention.
Single App Insights Instance Deployment (instead of an instance for each microservice).
Improved Documentation for the VSTS Deployment (updated setup.md - includes your changes from PR #8).
Updated Deploy.sh script and documentation.

No worries on rejecting the PR.  Most of what I did helped me become familiar with the solution.

**Comment by priyaananthasankar** [comment]
Thanks @Stewartarmbrecht , will review the web commits and single app insights instance. We wanted to keep one app insights instance per microservice that is inline with microservice architecture - so this can be included as a suggestion (with the list of suggestions in the readme doc)

**Comment by Stewartarmbrecht** [comment]
I have changed a branch in my fork that has the naming convention change.  I will close this and possibly submit another PR for the deployment improvements.

**Pull request closed without merging**
